name: flutter_disposables
version: 0.0.1
description: Disposable is responsible for auto disposing resources.
homepage: https://github.com/mosamuhana
repository: https://github.com/mosamuhana/flutter_disposables
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  disposables:
    git: https://github.com/mosamuhana/dart_disposables
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
